### ISSUE TITLE
How to index into Vector in O(1)?

### ISSUE THREAD

**Issue by AnthonyJacob** [ollef/sixten#104]
It is obvious, how should one iterate over vector but how do you index into it in O(1)?

**Comment by ollef** [comment]
Welcome! Good question. I got curious about this as well.

I first thought that LLVM would be able to optimise away the recursion and tried:

```haskell
type Maybe a = Nothing | Just a

index : forall a. (len : Nat) -> Vector len a -> Int -> Maybe a
index Zero MkUnit _ = Nothing
index (Succ n) (MkPair x xs) 0 = Just x
index @a (Succ n) (MkPair x xs) i = index @a n xs (subInt i 1)

index2 : forall a. (len : Nat) -> Vector len a -> Int -> a
index2 Zero MkUnit _ = fail _
index2 (Succ n) (MkPair x xs) 0 = x
index2 @a (Succ n) (MkPair x xs) i = index2 @a n xs (subInt i 1)
```

(The last `@a` bit is needed to satisfy the type checker... working on it!)

Sadly this was a bit optimistic. Looking at the LLVM assembly obtained from running `sixten compile -O2 -Sobj`, the optimised version is still recursive. It's possible that we could get Sixten to generate more optimisation-friendly LLVM assembly which would make this constant time, but that's not the case today. (In particular, there's an analysis pass in Sixten called `ReturnDirection` that detects when it's safe to return a value derived from a stack pointer given to you, which I think should apply to `index2`, but doesn't for some reason. It would make it much more likely that LLVM could do something good with it.)

Luckily, we've got escape hatches. Here's a way to do it:

```haskell
index3 : forall a. (len : Nat) -> Vector len a -> Int -> a
index3 @a len xs i = (C|
  memcpy(return_, $xs + $i * $(sizeOf a), $(sizeOf a));
|)

test = printInt (index3 (Succ (Succ (Succ Zero))) (MkPair 1 (MkPair 2 (MkPair 3 MkUnit))) 1)
```

Here we're taking advantage of how Sixten passes data to extern blocks: values of unknown size are passed as stack pointers of type `uint8_t*`, so knowing that the vector is an array of `a`s since it's flat in memory we can calculate the address of the `i`th `a` by plain old pointer arithmetic. If an extern block is expected to return a value of unknown type it becomes an out parameter called `return_`, so we copy the output there.

This is unsafe as it doesn't do bounds checking, but you get the idea. :)

**Comment by ollef** [comment]
I've created a more specific issue to improve the `ReturnDirection` pass which will hopefully make the recursive indexing operation be of the right form for LLVM to optimise it down to constant time.
