### ISSUE TITLE
String literals do not print out.

### ISSUE THREAD

**Issue by vmchale** [ollef/sixten#86]
I can write the following program to print "Hello, World!":

```
printString : String -> Unit
printString b = (C|
  puts((const char*)$b);
|)

someStr : String
someStr = (C| return_[0] = 'H' ;
              return_[1] = 'e' ;
              return_[2] = 'l' ;
              return_[3] = 'l' ;
              return_[4] = 'o' ;
              return_[5] = ' ' ;
              return_[6] = 'W' ;
              return_[7] = 'o' ;
              return_[8] = 'r' ;
              return_[9] = 'l' ;
              return_[10] = 'd' ;
              return_[11] = '!' ;
              |)

main = printString someStr
```

However, if I change `someStr` as follows, it stops working:

```
printString : String -> Unit
printString b = (C|
  puts((const char*)$b);
|)
someStr : String
someStr = "Hello, World!"
main = printString someStr
```

Is there a built-in function to print strings I am missing?

**Comment by ollef** [comment]
Hey, and welcome!

The problem with the functions that you gave is that `String` is not quite a C string.

`String` is defined [here](https://github.com/ollef/sixten/blob/master/rts/Builtin2.vix) and contains an `Array Byte`, where `Array` is a length and a pointer to an array of data the given length. So to get at the string as a character array, we can pattern match: `f (MkString (MkArray len data)) = ...`. However, `data` is not null-terminated, so we'll have to use lower-level functions like `write`, which also takes a length, instead of `puts`.

It's also very easy to do something illegal in extern C blocks since there are very few checks. The Sixten data is passed as-is, and the corresponding C type is chosen according to the rules given [here](https://github.com/ollef/sixten/blob/master/src/Backend/ExtractExtern.hs#L236). In essence, data of size 1, 2, 4, or 8 is passed directly as an `uintX_t`, and other data is passed as a stack pointer of type `uint8_t*`.

I just added a `printString` function [here](https://github.com/ollef/sixten/commit/3d1c1c7b499740fb4ee47bb7a76bf52bf3144f42).

Thanks for reaching out, and I hope this helps!

**Comment by vmchale** [comment]
Great, this looks good to me! Thanks!
